shamefullyHoist: true
strictPeerDependencies: false

packages:
  - .

ignoredBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - esbuild
  - protobufjs
  - unrs-resolver


onlyBuiltDependencies:
  - sharp
