minimumReleaseAge: 0
shamefullyHoist: true
strictPeerDependencies: false

packages:
  - .

allowBuilds:
  '@firebase/util': false
  '@parcel/watcher': false
  esbuild: false
  protobufjs: false
  sharp: true
  unrs-resolver: false
  vue-demi: false
