minimumReleaseAge: 0
shamefullyHoist: true
strictPeerDependencies: false

packages:
  - .

allowBuilds:
  '@firebase/util': false
  esbuild: false
  protobufjs: false
  sharp: true
  unrs-resolver: false
