// Language strings for English
export default {
  lang: "English",
  lang_code: "en",
  app_name: "Metrobus Balance",
  invitado: "[Guest]",
  config: "Settings",
  tarjetas: "Cards",
  perfil: "Profile",
  estado: "Status",
  salir: "Exit",
  nombre: "Name",
  numero_tarjeta: "Card number",
  add_tarjeta: "Add card",
  add: "Add",
  cancel: "Cancel",
  numero: "Number",
  tipo: "Type",
  fecha: "Last use",
  saldo: "Balance",
  actualizar_tarjetas: "Update cards",
  sesion: "Session",
  actualizando_tarjeta: "Updating card...",
  adding_tarjetas: "Adding cards...",
  adding_tarjeta: "Adding card...",
  login: "Log in",
  login_error: "The email address or password is incorrect. Please try again!",
  correo: "Email",
  password: "Password",
  password_check: "Confirm password",
  password_check_error: "Passwords do not match",
  password_limit: "Password must have at least 3 characters",
  no_cuenta: "Don't have an account?",
  registrate: "Sign up",
  no_registro: "Enter without registering",
  enter_email_password: "Enter your email and password",
  enter_account_info: "Enter your information to create an account",
  eliminar: "Delete",
  eliminar_tarjeta: "Delete card",
  eliminar_seguro: "Are you sure you want to delete this card?",
  editar: "Edit",
  editar_tarjeta: "Edit name",
  editada: "Card edited",
  tarjeta: "Card",
  info_tarjeta: "Card information",
  estado_contrato: "Contract status",
  tipo_tarjeta: "Card type",
  balance: "Card Balance",
  privacidad: "Privacy policy",
  acerca: "About",
  idioma: "Language",
  modo_oscuro: "Dark mode",
  language_prompt: "Select a language",
  languages: ["Spanish", "English"],
  guardar: "Save changes",
  dark_mode_desc: "Reduce glare and improve night vision",
  about_message: "\"Metrobus Balance\" is an app for checking balances and transactions for the metro and metrobús cards in Panama, designed and developed by Yizack Rangel. The two different logos were designed by Georlenys Martínez.\n\nBalance update may take up to 15 or 30 minutes to be reflected from the last transaction or action made with your card due to the update delay imposed by official sources.\n\nAll card data is obtained from the official source of the service on the consults site www.tarjetametrobus.com which offers this information throughout Panama. This app is unofficial, is not owned or endorsed by any government affiliation.",
  tarjeta_added: "Card added",
  tarjeta_actualizada: "Card updated",
  error_conexion: "Error, check your internet connection and try again",
  error: "An error has occurred",
  registrarse: "Sign up",
  tiene_cuenta: "Already have an account?",
  ingresa: "Log in",
  obligatorio: "This field is required",
  editando: "Applying changes...",
  eliminando: "Deleting...",
  eliminada: "Card deleted",
  iniciando_sesion: "Logging in...",
  tarjetas_vinculadas: "Linked cards",
  nota: "If you are not registered, your linked cards will only be stored in your phone's memory and will not be linked to any account. If you change phones, you will have to re-add your cards one by one. Register to link your card to your email.",
  nota2: "Metrobus Balance cannot access the password of any of its users because it passes through a hash algorithm (SHA-256) with a Salt and is stored already encrypted to protect your social networks in case someone unauthorized has access to our database.",
  informacion: "Information",
  movimientos: "Transactions",
  saldos: "Balances and transactions",
  fecha_mov: "Date",
  monto: "Amount",
  mov_4_semanas: "Transactions of the last 4 weeks",
  mov_notfound: "No transactions found",
  uso: "Usage",
  carga: "Load",
  carga_online: "Online load",
  puerta_trasera: "Back door",
  correo_incorrecto: "Invalid email address",
  correo_existe: "An account with this email already exists.",
  contrato_activo: "Active Contract",
  graficas: "Graphs",
  filtrar: "Filter by",
  d1: "1 day",
  d7: "7 days",
  d28: "28 days",
  grafica_saldo: "Balance change",
  saldo_hasta: "Balance up to",
  grafica_gastos: "Spendings",
  monto_gastado: "Amount spent",
  gasto_total: "Total spent",
  grafica_recargas: "Loads",
  monto_recargado: "Amount loaded",
  recarga_total: "Total loaded",
  por_dia: "Per day",
  por_hora: "Per hour",
  tarjeta_normal: "Normal card",
  tarjeta_rapipass: "Rapipass card",
  tarjetas_note: "Press your card for more information.",
  rango: "Range",
  no_cambio: "There were no changes in the balance.",
  grafica_nota: "Graphs do not include data for the current day.",
  error_tarjeta: "Invalid card number",
  error_tarjeta_unknown: "Card not available at this time",
  existe_tarjeta: "A card with this number already exists",
  version: "Version",
  change_pass: "Update password",
  current_pass: "Current password",
  new_pass: "New password",
  pass_updated: "Password updated",
  pass_error: "The current password is incorrect",
  updating_pass: "Updating password...",
  donar: "Donate",
  donacion: "Support the app",
  donar_desc: "Help keep this app alive! If you enjoy using this app and want to help keep it online, please consider making a donation to help with the development and costs of the server and database. Any amount you can donate will be greatly appreciated and will help us continue to offer this app to all of the users. Thank you for your support!",
  n_cuenta: "Account number",
  donar_bgeneral: "Use the following information to make your donation through bank transfer to third parties within the online banking app.",
  donar_nequi: "Use the following QR code by taking a screenshot or downloading the image to make your donation through the Nequi app.",
  copied: "Copied to clipboard",
  copiar_n: "Copy account number",
  download_qr: "Download QR code",
  delete_account: "Delete account",
  no_tarjetas: "No cards linked to this account yet.",
  delete_account_sure: "Are you sure you want to delete your account? This action cannot be undone and all your information will be permanently deleted.",
  deleting_account: "Deleting account...",
  account_deleted: "Account deleted",
  account_id: "Account identifier",
  olvido_pass: "Forgot password?",
  rutas: "MiBus Routes",
  rutas_corredores: "Corridor Routes",
  rutas_troncales: "Troncal Routes",
  rutas_complementarias: "Complementary Routes",
  info_ruta: "Route information",
  id: "ID",
  direccion: "Direction",
  axis: "Axis",
  departure: "Departure",
  arrival: "Arrival",
  location: "Location",
  destino: "Destination",
  direcciones: "Directions",
  no_direcciones: "No available directions found",
  results_notfound: "No results found",
  open_map: "Open in Google Maps",
  aviso_dir: "Please note that the directions may not be 100% accurate, so it is recommended to check the routes on the map before following the steps.",
  nueva_busqueda: "New search",
  creditos: "Credits",
  opensrc_credits: "Open source libraries that make this app possible and its development easier.",
  name_updated: "Name updated",
  buscar: "Search",
  use: "Use",
  panama: "Panama",
  mibus_info: "All information on the route network is collected from the MiBus website",
  recargar: "Top up card",
  buy: "Buy"
};
