// Language strings for English
export default {
  lang: "Spanish",
  lang_code: "es",
  app_name: "Metrobus Balance",
  invitado: "[Guest]",
  config: "Settings",
  tarjetas: "Cards",
  perfil: "Profile",
  estado: "Status",
  salir: "Exit",
  nombre: "Name",
  numero_tarjeta: "Card number",
  add_tarjeta: "Add card",
  add: "Add",
  cancel: "Cancel",
  numero: "Number",
  tipo: "Type",
  fecha: "Last use",
  saldo: "Balance",
  actualizar_tarjetas: "Update cards",
  sesion: "Session",
  actualizando_tarjetas: "Updating cards...",
  adding_tarjetas: "Adding card...",
  login: "Log in",
  login_error: "The email address or password is incorrect. Please try again!",
  correo: "Email",
  password: "Password",
  password_check: "Confirm password",
  password_check_error: "Passwords do not match",
  password_limit: "Password must have at least 3 characters",
  no_cuenta: "Don't have an account?",
  registrate: "Sign up",
  no_registro: "Enter without registering",
  enter_email_password: "Enter your email and password",
  eliminar: "Delete",
  eliminar_tarjeta: "Delete card",
  eliminar_seguro: "Are you sure you want to delete this card?",
  editar: "Edit",
  editar_tarjeta: "Edit card",
  tarjeta: "Card",
  info_tarjeta: "Card information",
  estado_contrato: "Contract status",
  tipo_tarjeta: "Card type",
  balance: "Card Balance",
  privacidad: "Privacy policies",
  acerca: "About",
  idioma: "Language",
  modo_oscuro: "Dark mode",
  language_prompt: "Select a language",
  languages: ["Spanish", "English"],
  guardar: "Save changes",
  dark_mode_desc: "Reduce glare and improve night vision",
  about_message: "\"Metrobus Balance\" is an app for checking balances and transactions for the metro and metrobús cards in Panama, designed and developed by Yizack Rangel. The two different logos were designed by Georlenys Martínez. All card data is obtained from the queries page of www.tarjetametrobus.com.",
  tarjeta_added: "Card added",
  tarjeta_actualizada: "Card updated",
  error_conexion: "Connection error. Please try again later.",
  error: "An error has occurred",
  registrarse: "Sign up",
  tiene_cuenta: "Already have an account?",
  ingresa: "Log in",
  obligatorio: "This field is required",
  editando: "Editing...",
  eliminando: "Deleting...",
  iniciando_sesion: "Logging in...",
  tarjetas_vinculadas: "Linked cards",
  nota: "If you are not registered, your linked cards will only be stored in your phone's memory and will not be linked to any account. If you change phones, you will have to re-add your cards one by one. Register to link your card to your email.",
  nota2: "Metrobus Balance cannot access the password of any of its users because it passes through a hash algorithm (SHA-256) with a Salt and is stored already encrypted to protect your social networks in case someone unauthorized has access to our database.",
  informacion: "Information",
  movimientos: "Transactions",
  saldos: "Balances and transactions",
  fecha_mov: "Date",
  monto: "Amount",
  mov_4_semanas: "Transactions of the last 4 weeks",
  mov_notfound: "No transactions found",
  uso: "Usage",
  carga: "Load",
  carga_online: "Online load",
  puerta_trasera: "Back door",
  correo_incorrecto: "Invalid email address",
  correo_existe: "An account with this email already exists.",
  contrato_activo: "Active Contract",
  graficas: "Graphs",
  filtrar: "Filter by",
  d1: "1 day",
  d7: "7 days",
  d28: "28 days",
  grafica_saldo: "Balance change",
  saldo_hasta: "Balance up to",
  grafica_gastos: "Expenses",
  monto_gastado: "Amount spent",
  gasto_total: "Total expense",
  grafica_recargas: "Recharges",
  monto_recargado: "Amount recharged",
  recarga_total: "Total recharge",
  por_dia: "Per day",
  por_hora: "Per hour",
  tarjeta_normal: "Normal card",
  tarjeta_rapipass: "Rapipass card",
  tarjetas_note: "Press your card for more information.",
  rango: "Range",
  no_cambio: "There were no changes in the balance.",
  grafica_nota: "Graphs do not include data for the current day.",
  error_tarjeta: "Invalid card number",
  existe_tarjeta: "A card with this number already exists",
  version: "Version"
};
