// Language strings for Spanish
export default {
  lang: "Español",
  lang_code: "es",
  app_name: "Saldo Metrobús",
  invitado: "[Invitado]",
  config: "Configuraciones",
  tarjetas: "Tarjetas",
  perfil: "Perfil",
  estado: "Estado",
  salir: "Salir",
  nombre: "Nombre",
  numero_tarjeta: "Número de tarjeta",
  add_tarjeta: "Agregar tarjeta",
  add: "Agregar",
  cancel: "Cancelar",
  numero: "Número",
  tipo: "Tipo",
  fecha: "Último uso",
  saldo: "Saldo",
  actualizar_tarjetas: "Actualizar tarjetas",
  sesion: "Sesión",
  actualizando_tarjeta: "Actualizando tarjeta...",
  adding_tarjetas: "Agregando tarjetas...",
  adding_tarjeta: "Agregando tarjeta...",
  login: "Iniciar sesión",
  login_error: "El correo electrónico o la contraseña son incorrectos. ¡Vuelve a intentarlo!",
  correo: "Correo electrónico",
  password: "Contraseña",
  password_check: "Confirmar contraseña",
  password_check_error: "Las contraseñas no coinciden",
  password_limit: "La contraseña debe tener al menos 3 caracteres",
  no_cuenta: "¿No tienes una cuenta?",
  registrate: "Regístrate",
  no_registro: "Entrar sin registrarse",
  enter_email_password: "Introduce tu correo y contraseña",
  enter_account_info: "Introduzca su información para crear una cuenta",
  eliminar: "Eliminar",
  eliminar_tarjeta: "Eliminar tarjeta",
  eliminar_seguro: "¿Estás seguro que deseas eliminar esta tarjeta?",
  editar: "Modificar",
  editar_tarjeta: "Cambiar nombre",
  editada: "Tarjeta modificada",
  tarjeta: "Tarjeta",
  info_tarjeta: "Información de la tarjeta",
  estado_contrato: "Estado de contrato",
  tipo_tarjeta: "Tipo de tarjeta",
  balance: "Balance",
  privacidad: "Política de privacidad",
  acerca: "Acerca de",
  idioma: "Idioma",
  modo_oscuro: "Modo oscuro",
  language_prompt: "Selecciona un idioma",
  languages: ["Español", "English"],
  guardar: "Guardar cambios",
  dark_mode_desc: "Reduce el resplandor y mejora la visión nocturna",
  about_message: "\"Saldo Metrobús\" es una app de consultas de saldo y movimientos para las tarjetas de Metro y Metrobús de Panamá, diseñada y desarrollada por Yizack Rangel. Los dos diferentes logos fueron diseñados por Georlenys Martínez\n\nLa actualización de saldo puede tardar hasta 15 o 30 minutos en reflejarse desde el último movimiento o acción realizada con tu tarjeta debido al retraso de actualización impuesto por las fuentes oficiales.\n\nTodos los datos de las tarjetas son obtenidos de la fuente oficial del servicio en el sitio a de consultas www.tarjetametrobus.com el cual ofrece esta información en todo Panamá. Esta aplicación no es oficial y no pertenece ni está respaldada por una afiliación gubernamental.",
  tarjeta_added: "Tarjeta agregada",
  tarjeta_actualizada: "Tarjeta actualizada",
  error_conexion: "Error, verifica tu conexión a internet e intenta de nuevo",
  error: "Ha ocurrido un error",
  registrarse: "Registrarse",
  tiene_cuenta: "¿Ya tienes una cuenta?",
  ingresa: "Ingresa",
  obligatorio: "Este campo es obligatorio",
  editando: "Aplicando cambios...",
  eliminando: "Eliminando...",
  eliminada: "Tarjeta eliminada",
  iniciando_sesion: "Iniciando sesión...",
  tarjetas_vinculadas: "Tarjetas vinculadas",
  nota: "Si no estás registrado, tus tarjetas vinculadas solamente serán almacenadas en la memoria de tu teléfono y no estarán vinculadas a ninguna cuenta, si cambias de teléfono tendrás que volver a añadir tus tarjetas una por una. Regístrate para vincular tu tarjeta a tu correo electrónico.",
  nota2: "Saldo Metrobús no puede acceder a la contraseña de ninguno de sus usuarios porque esta pasa por un algoritmo hash (SHA-256) con una Salt, y es almacenada ya cifrada para proteger tus redes sociales en caso de que alguien no autorizado tenga acceso a nuestra base de datos.",
  informacion: "Información",
  movimientos: "Movimientos",
  saldos: "Saldos y movimientos",
  fecha_mov: "Fecha",
  monto: "Monto",
  mov_4_semanas: "Movimientos de las últimas 4 semanas",
  mov_notfound: "No se encontraron movimientos",
  uso: "Uso",
  carga: "Carga",
  carga_online: "Carga online",
  puerta_trasera: "Puerta trasera",
  correo_incorrecto: "La dirección de correo no es válida",
  correo_existe: "Ya existe una cuenta con este correo",
  contrato_activo: "Contrato Activo",
  graficas: "Gráficas",
  filtrar: "Filtrar por",
  d1: "1 día",
  d7: "7 días",
  d28: "28 días",
  grafica_saldo: "Cambio de saldo",
  saldo_hasta: "Saldo hasta",
  grafica_gastos: "Gastos",
  monto_gastado: "Monto gastado",
  gasto_total: "Gasto total",
  grafica_recargas: "Cargas",
  monto_recargado: "Monto recargado",
  recarga_total: "Carga total",
  por_dia: "Por día",
  por_hora: "Por hora",
  tarjeta_normal: "Tarjeta Normal",
  tarjeta_rapipass: "Tarjeta Rapipass",
  tarjetas_note: "Presiona tu tarjeta para más información.",
  rango: "Rango",
  no_cambio: "No hubo cambios en el saldo.",
  grafica_nota: "Las gráficas no incluyen los datos del día actual.",
  error_tarjeta: "Número de tarjeta no válido",
  error_tarjeta_unknown: "Tarjeta no disponible en este momento",
  existe_tarjeta: "Ya existe una tarjeta con este número",
  version: "Versión",
  change_pass: "Cambiar contraseña",
  current_pass: "Contraseña actual",
  new_pass: "Nueva contraseña",
  pass_updated: "Contraseña actualizada",
  pass_error: "La contraseña actual es incorrecta",
  updating_pass: "Actualizando contraseña...",
  donar: "Donar",
  donacion: "Realiza una donación",
  donar_desc: "Si disfrutas usando esta app y quieres ayudar a mantenerla en línea, considera hacer una donación para ayudar con el desarrollo y los costos del servidor y base de datos. Cualquier cantidad que puedas donar será muy apreciada y ayudará a seguir ofreciendo esta app a todos de forma gratuita y sin anuncios. ¡Gracias por tu apoyo!",
  n_cuenta: "Número de cuenta",
  donar_bgeneral: "Utiliza la siguiente información para realizar tu donación a través de transferencia bancaria a terceros dentro de la app de la banca en línea.",
  donar_nequi: "Utiliza el siguiente código QR haciendo una captura de pantalla o descargando la imagen para realizar tu donación a través de la app de Nequi.",
  copied: "Copiado al portapapeles",
  copiar_n: "Copiar número",
  download_qr: "Descargar QR",
  delete_account: "Eliminar cuenta",
  no_tarjetas: "No existen tarjetas vinculadas a esta cuenta aún.",
  delete_account_sure: "¿Estás seguro que deseas eliminar tu cuenta? Esta acción no se puede deshacer y toda la información de tu cuenta será eliminada permanentemente.",
  deleting_account: "Eliminando cuenta...",
  account_deleted: "Cuenta eliminada",
  account_id: "Identificador de cuenta",
  olvido_pass: "¿Olvidaste tu contraseña?",
  rutas: "Rutas MiBus",
  rutas_corredores: "Rutas Corredores",
  rutas_troncales: "Rutas Troncales",
  rutas_complementarias: "Rutas Complementarias",
  info_ruta: "Información de la ruta",
  id: "Identificador",
  direccion: "Dirección",
  axis: "Eje",
  departure: "Salida",
  arrival: "Llegada",
  location: "Ubicación",
  destino: "Destino",
  direcciones: "Direcciones",
  no_direcciones: "No se encontraron direcciones disponibles",
  results_notfound: "No se encontraron resultados",
  open_map: "Abrir en Google Maps",
  aviso_dir: "Ten en cuenta que las direcciones pueden no ser 100% precisas, por lo que se recomienda verificar las rutas en el mapa antes de seguir los pasos.",
  nueva_busqueda: "Nueva búsqueda",
  creditos: "Créditos",
  opensrc_credits: "Librerías Open Source que hacen posible y facilitan el desarrollo de esta app y sus servicios",
  name_updated: "Nombre actualizado",
  buscar: "Buscar",
  use: "Usar"
};
