// Language strings for Spanish
export default {
  lang: "Español",
  lang_code: "es",
  app_name: "Saldo Metrobús",
  invitado: "[Invitado]",
  config: "Configuraciones",
  tarjetas: "Tarjetas",
  perfil: "Perfil",
  estado: "Estado",
  salir: "Salir",
  nombre: "Nombre",
  numero_tarjeta: "Número de tarjeta",
  add_tarjeta: "Agregar tarjeta",
  add: "Agregar",
  cancel: "Cancelar",
  numero: "Número",
  tipo: "Tipo",
  fecha: "Último uso",
  saldo: "Saldo",
  actualizar_tarjetas: "Actualizar tarjetas",
  sesion: "Sesión",
  actualizando_tarjeta: "Actualizando tarjeta...",
  adding_tarjetas: "Agregando tarjetas...",
  adding_tarjeta: "Agregando tarjeta...",
  login: "Iniciar sesión",
  login_error: "El correo electrónico o la contraseña son incorrectos. ¡Vuelve a intentarlo!",
  correo: "Correo",
  password: "Contraseña",
  password_check: "Confirmar contraseña",
  password_check_error: "Las contraseñas no coinciden",
  password_limit: "La contraseña debe tener al menos 3 caracteres",
  no_cuenta: "¿No tienes una cuenta?",
  registrate: "Regístrate",
  no_registro: "Entrar sin registrarse",
  enter_email_password: "Introduce tu correo y contraseña",
  eliminar: "Eliminar",
  eliminar_tarjeta: "Eliminar tarjeta",
  eliminar_seguro: "¿Estás seguro que deseas eliminar esta tarjeta?",
  editar: "Modificar",
  editar_tarjeta: "Cambiar nombre",
  editada: "Tarjeta modificada",
  tarjeta: "Tarjeta",
  info_tarjeta: "Información de la tarjeta",
  estado_contrato: "Estado de contrato",
  tipo_tarjeta: "Tipo de tarjeta",
  balance: "Balance",
  privacidad: "Políticas de privacidad",
  acerca: "Acerca de",
  idioma: "Idioma",
  modo_oscuro: "Modo oscuro",
  language_prompt: "Selecciona un idioma",
  languages: ["Español", "English"],
  guardar: "Guardar cambios",
  dark_mode_desc: "Reduce el resplandor y mejora la visión nocturna",
  about_message: "\"Saldo Metrobús\" es una app de consultas de saldo y movimientos para las tarjetas de metro y metrobús de Panamá, diseñada y desarrollada por Yizack Rangel. Los dos diferentes logos fueron diseñados por Georlenys Martínez.\n\nTodos los datos de las tarjetas son obtenidos de la página de consultas de www.tarjetametrobus.com.",
  tarjeta_added: "Tarjeta agregada",
  tarjeta_actualizada: "Tarjeta actualizada",
  error_conexion: "Error de conexión, verifica tu conexión a internet e intenta de nuevo",
  error: "Ha ocurrido un error",
  registrarse: "Registrarse",
  tiene_cuenta: "¿Ya tienes una cuenta?",
  ingresa: "Ingresa",
  obligatorio: "Este campo es obligatorio",
  editando: "Aplicando cambios...",
  eliminando: "Eliminando...",
  eliminada: "Tarjeta eliminada",
  iniciando_sesion: "Iniciando sesión...",
  tarjetas_vinculadas: "Tarjetas vinculadas",
  nota: "Si no estás registrado, tus tarjetas vinculadas solamente serán almacenadas en la memoria de tu teléfono y no estarán vinculadas a ninguna cuenta, si cambias de teléfono tendrás que volver a añadir tus tarjetas una por una. Regístrate para vincular tu tarjeta a tu correo electrónico.",
  nota2: "Saldo Metrobús no puede acceder a la contraseña de ninguno de sus usuarios porque esta pasa por un algoritmo hash (SHA-256) con una Salt, y es almacenada ya cifrada para proteger tus redes sociales en caso de que alguien no autorizado tenga acceso a nuestra base de datos.",
  informacion: "Información",
  movimientos: "Movimientos",
  saldos: "Saldos y movimientos",
  fecha_mov: "Fecha",
  monto: "Monto",
  mov_4_semanas: "Movimientos de las últimas 4 semanas",
  mov_notfound: "No se encontraron movimientos",
  uso: "Uso",
  carga: "Carga",
  carga_online: "Carga online",
  puerta_trasera: "Puerta trasera",
  correo_incorrecto: "La dirección de correo no es válida",
  correo_existe: "Ya existe una cuenta con este correo",
  contrato_activo: "Contrato Activo",
  graficas: "Gráficas",
  filtrar: "Filtrar por",
  d1: "1 día",
  d7: "7 días",
  d28: "28 días",
  grafica_saldo: "Cambio de saldo",
  saldo_hasta: "Saldo hasta",
  grafica_gastos: "Gastos",
  monto_gastado: "Monto gastado",
  gasto_total: "Gasto total",
  grafica_recargas: "Cargas",
  monto_recargado: "Monto recargado",
  recarga_total: "Carga total",
  por_dia: "Por día",
  por_hora: "Por hora",
  tarjeta_normal: "Tarjeta Normal",
  tarjeta_rapipass: "Tarjeta Rapipass",
  tarjetas_note: "Presiona tu tarjeta para más información.",
  rango: "Rango",
  no_cambio: "No hubo cambios en el saldo.",
  grafica_nota: "Las gráficas no incluyen los datos del día actual.",
  error_tarjeta: "Número de tarjeta no válido",
  existe_tarjeta: "Ya existe una tarjeta con este número",
  version: "Versión",
  change_pass: "Cambiar contraseña",
  current_pass: "Contraseña actual",
  new_pass: "Nueva contraseña",
  pass_updated: "Contraseña actualizada",
  pass_error: "La contraseña actual es incorrecta",
  updating_pass: "Actualizando contraseña..."
};
