name: Android Bundle

on:
  push:
    branches: [ main ]
    
jobs:
  # Android Bundle
  android-bundle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v7
    - uses: pnpm/setup@v2
      with:
        runtime: node@lts
        cache: true

    - name: MiBus Rutas 🚌
      run: node --run app:mibus

    - name: Build App ⚡
      run: node --run generate

    - name: Deploy Web Demo 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: .output/public

    - name: Clean output 🧹
      run: node --run app:clean

    - name: Capacitor 📲
      run: node --run sync

    - name: Version App 🔢
      run: |
          node --run app:version
          node --run trapeze

    - name: Setup java ☕
      uses: actions/setup-java@v5
      with:
        distribution: zulu
        java-version: 25

    - name: Bundle Android App 📦
      run: |
          cd android
          chmod +x ./gradlew
          ./gradlew app:bundleRelease --stacktrace

    - name: Extract Android Signing Key 🔑
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
        base64 -d android/release.jks.base64 > android/release.decrypted.jks

    - name: Sign Build 🔐
      run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -keypass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab key0

    - name: Upload Bundle 📤
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: android/app/build/outputs/bundle/release/app-release-signed.aab
        retention-days: 1
